# Generated by Django 4.2.1 on 2024-01-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='fr', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
